// ─── Translations ─────────────────────────────────────────────────────────────
export const T = {
  ar: {
    dir: 'rtl',
    appName: 'خبير الشبكة',
    appSub: 'نظام إدارة الجرد التقني',
    login: 'تسجيل الدخول',
    logout: 'تسجيل الخروج',
    username: 'اسم المستخدم',
    password: 'كلمة المرور',
    loginBtn: 'دخول',
    wrongCreds: 'اسم المستخدم أو كلمة المرور غير صحيحة',
    addDevice: 'إضافة جهاز',
    search: 'بحث...',
    all: 'الكل',
    online: 'متصل',
    offline: 'غير متصل',
    total: 'الإجمالي',
    exportExcel: 'تصدير CSV / Excel',
    exportPDF: 'تصدير PDF',
    saveSheets: 'حفظ في Sheets',
    sheetsSaved: '✓ تم الحفظ في Google Sheets',
    sheetsError: '✗ تأكد من إعداد Google Sheets API',
    users: 'المستخدمون',
    addUser: 'إضافة مستخدم',
    role: 'الصلاحية',
    admin: 'مسؤول',
    viewer: 'مشاهد',
    settings: 'الإعدادات',
    accountSettings: 'إعدادات الحساب',
    changePassword: 'تغيير كلمة المرور',
    oldPassword: 'كلمة المرور القديمة',
    newPassword: 'كلمة المرور الجديدة',
    confirmPassword: 'تأكيد كلمة المرور الجديدة',
    passwordChanged: '✓ تم تغيير كلمة المرور بنجاح',
    passwordError: '✗ كلمة المرور القديمة غير صحيحة',
    passwordMismatch: '✗ كلمات المرور الجديدة غير متطابقة',
    passwordShort: '✗ كلمة المرور يجب أن تكون 6 أحرف على الأقل',
    sheetsUrl: 'رابط Google Sheets API',
    sheetsPlaceholder: 'https://script.google.com/macros/s/YOUR_SCRIPT_ID/exec',
    save: 'حفظ',
    cancel: 'إلغاء',
    noResults: 'لا توجد نتائج',
    confirmDelete: 'هل تريد حذف هذا الجهاز؟',
    delete: 'حذف',
    edit: 'تعديل',
    dashboard: 'الرئيسية',
    inventory: 'الجرد',
    auditLog: 'سجل العمليات',
    auditEmpty: 'لا توجد عمليات مسجلة بعد',
    darkMode: 'الوضع الداكن',
    lightMode: 'الوضع الفاتح',
    colorTheme: 'لون الواجهة',
    table: {
      name: 'اسم الجهاز', type: 'النوع', status: 'الحالة',
      serial: 'الرقم التسلسلي', location: 'الموقع', connection: 'الاتصال',
      actions: 'إجراءات', employee: 'الموظف المسؤول', empId: 'الرقم الوظيفي',
      addedBy: 'أضيف بواسطة', addedAt: 'تاريخ الإضافة', attachment: 'الملف', notes: 'ملاحظات',
    },
    modal: {
      addTitle: 'إضافة جهاز جديد', editTitle: 'تعديل الجهاز',
      name: 'اسم الجهاز', type: 'النوع', status: 'الحالة',
      serial: 'الرقم التسلسلي', location: 'الموقع', connection: 'متصل بالشبكة',
      employee: 'اسم الموظف المسؤول', empId: 'الرقم الوظيفي',
      attachment: 'إرفاق ملف (صورة أو PDF)',
      attachmentHint: 'اسحب وأفلت أو اضغط للاختيار',
      uploading: 'جاري الرفع...',
      uploadDone: '✓ تم الرفع',
      uploadError: '✗ فشل الرفع',
      viewFile: 'عرض الملف',
      save: 'حفظ', cancel: 'إلغاء',
      typeHint: 'اكتب أو اختر من القائمة',
      required: 'الاسم والرقم التسلسلي مطلوبان',
    },
    audit: {
      action: 'العملية', device: 'الجهاز', oldVal: 'القيمة القديمة',
      newVal: 'القيمة الجديدة', user: 'المستخدم', time: 'الوقت',
      added: 'إضافة', edited: 'تعديل', deleted: 'حذف', passwordChanged: 'تغيير كلمة المرور',
    },
    deviceTypes: {
      router: 'راوتر', switch: 'سويتش', ap: 'نقطة وصول', firewall: 'جدار حماية',
      server: 'خادم', nas: 'أجهزة تخزين', ups: 'وحدات الطاقة', rack: 'كبائن الشبكة',
      phone: 'هاتف IP', computer: 'كمبيوتر', accessory: 'ملحق',
    },
    statuses: { new: 'جديد', used: 'مستخدم', damaged: 'تالف' },
    locations: { warehouse: 'المستودع', main: 'المبنى الرئيسي', factory: 'المصنع' },
  },
  en: {
    dir: 'ltr',
    appName: 'Net Expert',
    appSub: 'Technical Inventory Management',
    login: 'Login',
    logout: 'Logout',
    username: 'Username',
    password: 'Password',
    loginBtn: 'Sign In',
    wrongCreds: 'Invalid username or password',
    addDevice: 'Add Device',
    search: 'Search...',
    all: 'All',
    online: 'Online',
    offline: 'Offline',
    total: 'Total',
    exportExcel: 'Export CSV / Excel',
    exportPDF: 'Export PDF',
    saveSheets: 'Save to Sheets',
    sheetsSaved: '✓ Saved to Google Sheets',
    sheetsError: '✗ Check Google Sheets API config',
    users: 'Users',
    addUser: 'Add User',
    role: 'Role',
    admin: 'Admin',
    viewer: 'Viewer',
    settings: 'Settings',
    accountSettings: 'Account Settings',
    changePassword: 'Change Password',
    oldPassword: 'Current Password',
    newPassword: 'New Password',
    confirmPassword: 'Confirm New Password',
    passwordChanged: '✓ Password changed successfully',
    passwordError: '✗ Current password is incorrect',
    passwordMismatch: '✗ New passwords do not match',
    passwordShort: '✗ Password must be at least 6 characters',
    sheetsUrl: 'Google Sheets API URL',
    sheetsPlaceholder: 'https://script.google.com/macros/s/YOUR_SCRIPT_ID/exec',
    save: 'Save',
    cancel: 'Cancel',
    noResults: 'No results found',
    confirmDelete: 'Delete this device?',
    delete: 'Delete',
    edit: 'Edit',
    dashboard: 'Dashboard',
    inventory: 'Inventory',
    auditLog: 'Audit Log',
    auditEmpty: 'No operations recorded yet',
    darkMode: 'Dark Mode',
    lightMode: 'Light Mode',
    colorTheme: 'Color Theme',
    table: {
      name: 'Device Name', type: 'Type', status: 'Status',
      serial: 'Serial Number', location: 'Location', connection: 'Connection',
      actions: 'Actions', employee: 'Responsible Employee', empId: 'Employee ID',
      addedBy: 'Added By', addedAt: 'Date Added', attachment: 'File', notes: 'Notes',
    },
    modal: {
      addTitle: 'Add New Device', editTitle: 'Edit Device',
      name: 'Device Name', type: 'Type', status: 'Status',
      serial: 'Serial Number', location: 'Location', connection: 'Connected to Network',
      employee: 'Responsible Employee Name', empId: 'Employee ID',
      attachment: 'Attach File (Image or PDF)',
      attachmentHint: 'Drag & drop or click to choose',
      uploading: 'Uploading...',
      uploadDone: '✓ Uploaded',
      uploadError: '✗ Upload failed',
      viewFile: 'View File',
      save: 'Save', cancel: 'Cancel',
      typeHint: 'Type or select from list',
      required: 'Name and Serial Number are required',
    },
    audit: {
      action: 'Action', device: 'Device', oldVal: 'Old Value',
      newVal: 'New Value', user: 'User', time: 'Time',
      added: 'Added', edited: 'Edited', deleted: 'Deleted', passwordChanged: 'Password Changed',
    },
    deviceTypes: {
      router: 'Router', switch: 'Switch', ap: 'Access Point', firewall: 'Firewall',
      server: 'Server', nas: 'NAS Storage', ups: 'UPS', rack: 'Rack Cabinet',
      phone: 'IP Phone', computer: 'Computer', accessory: 'Accessory',
    },
    statuses: { new: 'New', used: 'In Use', damaged: 'Damaged' },
    locations: { warehouse: 'Warehouse', main: 'Main Building', factory: 'Factory' },
  },
};

// ─── Initial Data ──────────────────────────────────────────────────────────────
export const INITIAL_DEVICES = [
  { id:1,  name:'Cisco ISR 4331',       type:'router',    status:'used',    serial:'FTX1901A011',  location:'main',      online:true,  employee:'أحمد العمري',   empId:'EMP001', addedBy:'Badr', addedAt:'2024-01-15T08:30:00', attachmentUrl:'', attachmentName:'', attachmentLabel:'', notes:'' },
  { id:2,  name:'Cisco Catalyst 2960',  type:'switch',    status:'used',    serial:'FTX1901A012',  location:'main',      online:true,  employee:'سالم القحطاني', empId:'EMP002', addedBy:'Badr', addedAt:'2024-01-15T09:00:00', attachmentUrl:'', attachmentName:'', attachmentLabel:'', notes:'' },
  { id:3,  name:'Cisco Catalyst 3750',  type:'switch',    status:'used',    serial:'FTX1901A013',  location:'factory',   online:true,  employee:'خالد المطيري',  empId:'EMP003', addedBy:'Badr', addedAt:'2024-01-16T10:00:00', attachmentUrl:'', attachmentName:'', attachmentLabel:'', notes:'' },
  { id:4,  name:'Ubiquiti UAP-AC-PRO',  type:'ap',        status:'used',    serial:'F09FC2A0B001', location:'main',      online:true,  employee:'أحمد العمري',   empId:'EMP001', addedBy:'Badr', addedAt:'2024-01-20T11:00:00', attachmentUrl:'', attachmentName:'', attachmentLabel:'', notes:'' },
  { id:5,  name:'Ubiquiti UAP Lite',    type:'ap',        status:'new',     serial:'F09FC2A0B002', location:'warehouse', online:false, employee:'',              empId:'',       addedBy:'Badr', addedAt:'2024-02-01T08:00:00', attachmentUrl:'', attachmentName:'', attachmentLabel:'', notes:'' },
  { id:6,  name:'Fortinet FG-60F',      type:'firewall',  status:'used',    serial:'FG60FTK19A001',location:'main',      online:true,  employee:'سالم القحطاني', empId:'EMP002', addedBy:'Badr', addedAt:'2024-02-05T09:30:00', attachmentUrl:'', attachmentName:'', attachmentLabel:'', notes:'' },
  { id:7,  name:'Dell PowerEdge R740',  type:'server',    status:'used',    serial:'DLL7400S001',  location:'main',      online:true,  employee:'خالد المطيري',  empId:'EMP003', addedBy:'Badr', addedAt:'2024-02-10T10:00:00', attachmentUrl:'', attachmentName:'', attachmentLabel:'', notes:'' },
  { id:8,  name:'Synology DS920+',      type:'nas',       status:'used',    serial:'SYN9200N001',  location:'main',      online:true,  employee:'أحمد العمري',   empId:'EMP001', addedBy:'Badr', addedAt:'2024-02-15T11:00:00', attachmentUrl:'', attachmentName:'', attachmentLabel:'', notes:'' },
  { id:9,  name:'APC Smart-UPS 1500',   type:'ups',       status:'used',    serial:'APC1500U001',  location:'main',      online:true,  employee:'سالم القحطاني', empId:'EMP002', addedBy:'Badr', addedAt:'2024-03-01T08:00:00', attachmentUrl:'', attachmentName:'', attachmentLabel:'', notes:'' },
  { id:10, name:'APC Smart-UPS 750',    type:'ups',       status:'new',     serial:'APC750U002',   location:'warehouse', online:false, employee:'',              empId:'',       addedBy:'Badr', addedAt:'2024-03-05T09:00:00', attachmentUrl:'', attachmentName:'', attachmentLabel:'', notes:'' },
  { id:11, name:'StarTech 42U Rack',    type:'rack',      status:'used',    serial:'STC42R001',    location:'main',      online:false, employee:'خالد المطيري',  empId:'EMP003', addedBy:'Badr', addedAt:'2024-03-10T10:00:00', attachmentUrl:'', attachmentName:'', attachmentLabel:'', notes:'' },
  { id:12, name:'Cisco IP Phone 7942',  type:'phone',     status:'used',    serial:'FCH2201P101',  location:'main',      online:true,  employee:'أحمد العمري',   empId:'EMP001', addedBy:'Badr', addedAt:'2024-03-15T11:00:00', attachmentUrl:'', attachmentName:'', attachmentLabel:'', notes:'' },
  { id:13, name:'Cisco IP Phone 7945',  type:'phone',     status:'damaged', serial:'FCH2201P102',  location:'warehouse', online:false, employee:'',              empId:'',       addedBy:'Badr', addedAt:'2024-03-20T08:00:00', attachmentUrl:'', attachmentName:'', attachmentLabel:'', notes:'يحتاج إصلاح' },
  { id:14, name:'Dell OptiPlex 7090',   type:'computer',  status:'used',    serial:'DLL9900C001',  location:'main',      online:true,  employee:'سالم القحطاني', empId:'EMP002', addedBy:'Badr', addedAt:'2024-04-01T09:00:00', attachmentUrl:'', attachmentName:'', attachmentLabel:'', notes:'' },
  { id:15, name:'HP EliteDesk 800 G6',  type:'computer',  status:'used',    serial:'HPE8006C001',  location:'factory',   online:true,  employee:'خالد المطيري',  empId:'EMP003', addedBy:'Badr', addedAt:'2024-04-05T10:00:00', attachmentUrl:'', attachmentName:'', attachmentLabel:'', notes:'' },
  { id:16, name:'Lenovo ThinkCentre',   type:'computer',  status:'new',     serial:'LNV9900C001',  location:'warehouse', online:false, employee:'',              empId:'',       addedBy:'Badr', addedAt:'2024-04-10T11:00:00', attachmentUrl:'', attachmentName:'', attachmentLabel:'', notes:'جديد في المستودع' },
  { id:17, name:'HP LaserJet Pro M404', type:'accessory', status:'used',    serial:'HPM404A001',   location:'main',      online:false, employee:'أحمد العمري',   empId:'EMP001', addedBy:'Badr', addedAt:'2024-04-15T08:00:00', attachmentUrl:'', attachmentName:'', attachmentLabel:'', notes:'' },
  { id:18, name:'Canon DR-C225 II',     type:'accessory', status:'damaged', serial:'CAN225D001',   location:'warehouse', online:false, employee:'',              empId:'',       addedBy:'Badr', addedAt:'2024-04-20T09:00:00', attachmentUrl:'', attachmentName:'', attachmentLabel:'', notes:'عطل في وحدة المسح' },
];

export const INITIAL_USERS = [
  { id:1, username:'Badr',    password:'BADR050982538', role:'admin',  name:'Badr',         email:'admin@netexpert.com' },
  { id:2, username:'viewer1', password:'view123',       role:'viewer', name:'موظف التقنية', email:'it@netexpert.com'    },
];

export const TYPE_COLORS = {
  router:   { bg:'bg-cyan-500/15',    text:'text-cyan-400',    border:'border-cyan-500/30'    },
  switch:   { bg:'bg-blue-500/15',    text:'text-blue-400',    border:'border-blue-500/30'    },
  ap:       { bg:'bg-teal-500/15',    text:'text-teal-400',    border:'border-teal-500/30'    },
  firewall: { bg:'bg-red-500/15',     text:'text-red-400',     border:'border-red-500/30'     },
  server:   { bg:'bg-violet-500/15',  text:'text-violet-400',  border:'border-violet-500/30'  },
  nas:      { bg:'bg-purple-500/15',  text:'text-purple-400',  border:'border-purple-500/30'  },
  ups:      { bg:'bg-amber-500/15',   text:'text-amber-400',   border:'border-amber-500/30'   },
  rack:     { bg:'bg-stone-500/15',   text:'text-stone-400',   border:'border-stone-500/30'   },
  phone:    { bg:'bg-emerald-500/15', text:'text-emerald-400', border:'border-emerald-500/30' },
  computer: { bg:'bg-sky-500/15',     text:'text-sky-400',     border:'border-sky-500/30'     },
  accessory:{ bg:'bg-pink-500/15',    text:'text-pink-400',    border:'border-pink-500/30'    },
};

export const LOC_COLORS = {
  warehouse: 'bg-amber-500/10 text-amber-400 border-amber-500/25',
  main:      'bg-cyan-500/10 text-cyan-400 border-cyan-500/25',
  factory:   'bg-violet-500/10 text-violet-400 border-violet-500/25',
};
