// ─── Translations ─────────────────────────────────────────────────────────────
export const T = {
  ar: {
    dir: 'rtl',
    appName: 'خبير الشبكة',
    appSub: 'نظام إدارة الجرد التقني',
    login: 'تسجيل الدخول',
    logout: 'تسجيل الخروج',
    username: 'اسم المستخدم',
    password: 'كلمة المرور',
    loginBtn: 'دخول',
    wrongCreds: 'اسم المستخدم أو كلمة المرور غير صحيحة',
    addDevice: 'إضافة جهاز',
    search: 'بحث...',
    all: 'الكل',
    online: 'متصل',
    offline: 'غير متصل',
    total: 'الإجمالي',
    exportExcel: 'تصدير Excel',
    exportPDF: 'تصدير PDF',
    saveSheets: 'حفظ في Sheets',
    sheetsSaved: '✓ تم الحفظ في Google Sheets',
    sheetsError: '✗ تأكد من إعداد Google Sheets API',
    users: 'المستخدمون',
    addUser: 'إضافة مستخدم',
    role: 'الصلاحية',
    admin: 'مسؤول',
    viewer: 'مشاهد',
    settings: 'الإعدادات',
    sheetsUrl: 'رابط Google Sheets API',
    sheetsPlaceholder: 'https://script.google.com/macros/s/YOUR_SCRIPT_ID/exec',
    save: 'حفظ',
    cancel: 'إلغاء',
    noResults: 'لا توجد نتائج',
    confirmDelete: 'هل تريد حذف هذا الجهاز؟',
    delete: 'حذف',
    edit: 'تعديل',
    dashboard: 'الرئيسية',
    inventory: 'الجرد',
    table: {
      name: 'اسم الجهاز', type: 'النوع', status: 'الحالة',
      serial: 'الرقم التسلسلي', location: 'الموقع', connection: 'الاتصال', actions: 'إجراءات',
    },
    modal: {
      addTitle: 'إضافة جهاز جديد', editTitle: 'تعديل الجهاز',
      name: 'اسم الجهاز', type: 'النوع', status: 'الحالة',
      serial: 'الرقم التسلسلي', location: 'الموقع', connection: 'متصل بالشبكة',
      save: 'حفظ', cancel: 'إلغاء',
    },
    sections: { network: 'أجهزة الشبكة', phones: 'هواتف IP', computers: 'الكمبيوتر', accessories: 'الملحقات' },
    deviceTypes: {
      router: 'راوتر', switch: 'سويتش', ap: 'نقطة وصول', firewall: 'جدار حماية',
      server: 'خادم', nas: 'أجهزة تخزين', ups: 'وحدات الطاقة', rack: 'كبائن الشبكة',
      phone: 'هاتف IP', computer: 'كمبيوتر', accessory: 'ملحق',
    },
    statuses: { new: 'جديد', used: 'مستخدم', damaged: 'تالف' },
    locations: { warehouse: 'المستودع', main: 'المبنى الرئيسي', factory: 'المصنع' },
  },
  en: {
    dir: 'ltr',
    appName: 'Net Expert',
    appSub: 'Technical Inventory Management',
    login: 'Login',
    logout: 'Logout',
    username: 'Username',
    password: 'Password',
    loginBtn: 'Sign In',
    wrongCreds: 'Invalid username or password',
    addDevice: 'Add Device',
    search: 'Search...',
    all: 'All',
    online: 'Online',
    offline: 'Offline',
    total: 'Total',
    exportExcel: 'Export Excel',
    exportPDF: 'Export PDF',
    saveSheets: 'Save to Sheets',
    sheetsSaved: '✓ Saved to Google Sheets',
    sheetsError: '✗ Check Google Sheets API config',
    users: 'Users',
    addUser: 'Add User',
    role: 'Role',
    admin: 'Admin',
    viewer: 'Viewer',
    settings: 'Settings',
    sheetsUrl: 'Google Sheets API URL',
    sheetsPlaceholder: 'https://script.google.com/macros/s/YOUR_SCRIPT_ID/exec',
    save: 'Save',
    cancel: 'Cancel',
    noResults: 'No results found',
    confirmDelete: 'Delete this device?',
    delete: 'Delete',
    edit: 'Edit',
    dashboard: 'Dashboard',
    inventory: 'Inventory',
    table: {
      name: 'Device Name', type: 'Type', status: 'Status',
      serial: 'Serial Number', location: 'Location', connection: 'Connection', actions: 'Actions',
    },
    modal: {
      addTitle: 'Add New Device', editTitle: 'Edit Device',
      name: 'Device Name', type: 'Type', status: 'Status',
      serial: 'Serial Number', location: 'Location', connection: 'Connected to Network',
      save: 'Save', cancel: 'Cancel',
    },
    sections: { network: 'Network Devices', phones: 'IP Phones', computers: 'Computers', accessories: 'Accessories' },
    deviceTypes: {
      router: 'Router', switch: 'Switch', ap: 'Access Point', firewall: 'Firewall',
      server: 'Server', nas: 'NAS Storage', ups: 'UPS', rack: 'Rack Cabinet',
      phone: 'IP Phone', computer: 'Computer', accessory: 'Accessory',
    },
    statuses: { new: 'New', used: 'In Use', damaged: 'Damaged' },
    locations: { warehouse: 'Warehouse', main: 'Main Building', factory: 'Factory' },
  },
};

// ─── Initial Data ──────────────────────────────────────────────────────────────
export const INITIAL_DEVICES = [
  { id: 1,  name: 'Cisco ISR 4331',      type: 'router',   status: 'used',    serial: 'FTX1901A011', location: 'main',      online: true  },
  { id: 2,  name: 'Cisco Catalyst 2960', type: 'switch',   status: 'used',    serial: 'FTX1901A012', location: 'main',      online: true  },
  { id: 3,  name: 'Cisco Catalyst 3750', type: 'switch',   status: 'used',    serial: 'FTX1901A013', location: 'factory',   online: true  },
  { id: 4,  name: 'Ubiquiti UAP-AC-PRO', type: 'ap',       status: 'used',    serial: 'F09FC2A0B001', location: 'main',      online: true  },
  { id: 5,  name: 'Ubiquiti UAP Lite',   type: 'ap',       status: 'stored',  serial: 'F09FC2A0B002', location: 'warehouse', online: false },
  { id: 6,  name: 'Fortinet FG-60F',     type: 'firewall', status: 'used',    serial: 'FG60FTK19A001',location: 'main',      online: true  },
  { id: 7,  name: 'Dell PowerEdge R740', type: 'server',   status: 'used',    serial: 'DLL7400S001', location: 'main',      online: true  },
  { id: 8,  name: 'Synology DS920+',     type: 'nas',      status: 'used',    serial: 'SYN9200N001', location: 'main',      online: true  },
  { id: 9,  name: 'APC Smart-UPS 1500',  type: 'ups',      status: 'used',    serial: 'APC1500U001', location: 'main',      online: true  },
  { id: 10, name: 'APC Smart-UPS 750',   type: 'ups',      status: 'stored',  serial: 'APC750U002',  location: 'warehouse', online: false },
  { id: 11, name: 'StarTech 42U Rack',   type: 'rack',     status: 'used',    serial: 'STC42R001',   location: 'main',      online: false },
  { id: 12, name: 'Cisco IP Phone 7942', type: 'phone',    status: 'used',    serial: 'FCH2201P101', location: 'main',      online: true  },
  { id: 13, name: 'Cisco IP Phone 7945', type: 'phone',    status: 'damaged', serial: 'FCH2201P102', location: 'warehouse', online: false },
  { id: 14, name: 'Dell OptiPlex 7090',  type: 'computer', status: 'used',    serial: 'DLL9900C001', location: 'main',      online: true  },
  { id: 15, name: 'HP EliteDesk 800 G6', type: 'computer', status: 'used',    serial: 'HPE8006C001', location: 'factory',   online: true  },
  { id: 16, name: 'Lenovo ThinkCentre',  type: 'computer', status: 'new',     serial: 'LNV9900C001', location: 'warehouse', online: false },
  { id: 17, name: 'HP LaserJet Pro M404',type: 'accessory',status: 'used',    serial: 'HPM404A001',  location: 'main',      online: false },
  { id: 18, name: 'Canon DR-C225 II',    type: 'accessory',status: 'damaged', serial: 'CAN225D001',  location: 'warehouse', online: false },
];

export const INITIAL_USERS = [
  { id: 1, username: 'admin',   password: 'admin123', role: 'admin',  name: 'المسؤول الرئيسي' },
  { id: 2, username: 'viewer1', password: 'view123',  role: 'viewer', name: 'موظف المستودع'   },
];

export const TYPE_GROUPS = {
  network:     ['router','switch','ap','firewall'],
  servers:     ['server','nas'],
  power:       ['ups','rack'],
  endpoints:   ['phone','computer','accessory'],
};

export const TYPE_COLORS = {
  router:   { ring: 'ring-cyan-500',    bg: 'bg-cyan-500/15',    text: 'text-cyan-400',    border: 'border-cyan-500/30'    },
  switch:   { ring: 'ring-blue-500',    bg: 'bg-blue-500/15',    text: 'text-blue-400',    border: 'border-blue-500/30'    },
  ap:       { ring: 'ring-teal-500',    bg: 'bg-teal-500/15',    text: 'text-teal-400',    border: 'border-teal-500/30'    },
  firewall: { ring: 'ring-red-500',     bg: 'bg-red-500/15',     text: 'text-red-400',     border: 'border-red-500/30'     },
  server:   { ring: 'ring-violet-500',  bg: 'bg-violet-500/15',  text: 'text-violet-400',  border: 'border-violet-500/30'  },
  nas:      { ring: 'ring-purple-500',  bg: 'bg-purple-500/15',  text: 'text-purple-400',  border: 'border-purple-500/30'  },
  ups:      { ring: 'ring-amber-500',   bg: 'bg-amber-500/15',   text: 'text-amber-400',   border: 'border-amber-500/30'   },
  rack:     { ring: 'ring-stone-400',   bg: 'bg-stone-500/15',   text: 'text-stone-400',   border: 'border-stone-500/30'   },
  phone:    { ring: 'ring-emerald-500', bg: 'bg-emerald-500/15', text: 'text-emerald-400', border: 'border-emerald-500/30' },
  computer: { ring: 'ring-sky-500',     bg: 'bg-sky-500/15',     text: 'text-sky-400',     border: 'border-sky-500/30'     },
  accessory:{ ring: 'ring-pink-500',    bg: 'bg-pink-500/15',    text: 'text-pink-400',    border: 'border-pink-500/30'    },
};

export const LOC_COLORS = {
  warehouse: 'bg-amber-500/10 text-amber-400 border-amber-500/25',
  main:      'bg-cyan-500/10 text-cyan-400 border-cyan-500/25',
  factory:   'bg-violet-500/10 text-violet-400 border-violet-500/25',
};
